name: Deploy project to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t adidas-subscriptions-webapp .
    - name: Tag Docker image
      run: docker tag adidas-subscriptions-webapp enjuanes/adidas-subscriptions-webapp
    - name: DockerHub login
      run: echo '${{ secrets.DOCKER_ID_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_ID_USER }} --password-stdin 
    - name: Push Docker image to DockerHub
      run: docker push enjuanes/adidas-subscriptions-webapp
    - name: Add SSH key
      run: |
        mkdir -p $HOME/.ssh
        ssh-keyscan adidas-tech-challenge.davidenjuan.es >> $HOME/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
    - name: Pull and deploy image
      run: ssh ubuntu@adidas-tech-challenge.davidenjuan.es "cd /home/ubuntu/Adidas/docker-compose && docker-compose pull web-app && docker-compose up -d web-app"
